source("dataLoad.r")
prev_locale <- Sys.getlocale(category = "LC_ALL")
Sys.setlocale(category = "LC_ALL", locale = "C")
png("myplots/plot3.png",width = 480, height = 480, units = "px")
with(pw_data,plot(timestamp,Sub_metering_1,type = "l",xlab="",ylab="Energy sub metering",col="black"))
with(pw_data,lines(timestamp,Sub_metering_2,type="l",col="red"))
with(pw_data,lines(timestamp,Sub_metering_3,type="l",col="blue"))
legend(x="topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=c(1,1,1))
dev.off()
Sys.setlocale(category = "LC_ALL", locale = prev_locale)